@id=0623a6ef-f5a4-4b6e-88c6-b09fc538c808
PUT http://localhost:5147/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Vegan Sunshine 2",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}